#!/usr/bin/env python3
"""Least-norm source cost and profile-ray audit for the TPC-295 image.

TPC-295 proved that the unrestricted finite correlation map is onto.  This
release measures the cost of the explicit least-norm preimage and compares
the weighted sign targets with the one-dimensional ray generated by the
frozen source vector.  The cost/profile atlas is high-precision numerical
evidence; the source-energy inequalities are exact linear algebra.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import multiprocessing as mp_pool
import os
import sys
from fractions import Fraction
from pathlib import Path
from typing import Any

import mpmath as mp

if hasattr(sys, "set_int_max_str_digits"):
    sys.set_int_max_str_digits(0)

PROJECT = Path(__file__).resolve().parents[1]
ROOT = PROJECT.parents[1]
PARENT_CODE = ROOT / (
    "papers/tpc-295-source-correlation-image-audit/code/"
    "tpc295_source_correlation_image_certificate.py")
PARENT_RESULT = ROOT / (
    "papers/tpc-295-source-correlation-image-audit/results/"
    "tpc295_certificate.json")
ENGINE_CODE = ROOT / (
    "papers/tpc-268-finite-cutoff-sensitivity-obstruction/code/"
    "tpc268_cutoff_sensitivity_certificate.py")
RESULT = PROJECT / "results/tpc296_certificate.json"

PARENT_CODE_SHA256 = (
    "3cdb1ea78f0fd04fd70d268997ffb1ee6842c2b523dd0c69a28adff6fab8c6c4")
PARENT_RESULT_SHA256 = (
    "5e0e723aa93f221f77d5ee84cf20b0ed968adae67669d04e9d70032128212aff")
ENGINE_CODE_SHA256 = (
    "e0ec5400ab6a052fb0e2afc82035dc1428085423d43a3bf86e34d0f7e55d2ee3")
STATUS = (
    "PROVED_EXACT_LEAST_NORM_SOURCE_BUDGET_AND_SOURCE_ENERGY_TRADEOFF_PLUS_"
    "NUMERICALLY_CERTIFIED_FINITE_COST_PROFILE_ATLAS")
SCHEMA = "TPC296_SOURCE_NORM_BUDGET_CERTIFICATE_V1"
ROUND2_CLUE = "TEST_RESTRICTED_PROFILE_DIMENSION_AND_GROWING_SOURCE_BUDGET"
MODULI = (1000000007, 998244353)
MP_DPS = 70
INTERVAL_RELATIVE_RADIUS = mp.mpf("1e-18")
BUDGET_RATIO_THRESHOLD = mp.mpf("1e-3")
PROFILE_RMS_THRESHOLD = mp.mpf("0.9")

parent_spec = importlib.util.spec_from_file_location(
    "frozen_tpc295_for_tpc296", PARENT_CODE)
if parent_spec is None or parent_spec.loader is None:
    raise RuntimeError("TPC-295 parent unavailable")
PARENT = importlib.util.module_from_spec(parent_spec)
parent_spec.loader.exec_module(PARENT)
ENGINE = PARENT.ENGINE


class CheckFailure(RuntimeError):
    pass


def need(condition: bool, message: str) -> None:
    if type(condition) is not bool or not condition:
        raise CheckFailure(message)


def canonical(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=True, sort_keys=True,
                       separators=(",", ":")) + "\n").encode("ascii")


def digest(data: bytes) -> str:
    return hashlib.sha256(data.replace(b"\r\n", b"\n").replace(
        b"\r", b"\n")).hexdigest()


def parent_lock() -> dict[str, Any]:
    need(digest(PARENT_CODE.read_bytes()) == PARENT_CODE_SHA256,
         "TPC295 code provenance")
    raw = PARENT_RESULT.read_bytes()
    need(digest(raw) == PARENT_RESULT_SHA256, "TPC295 result provenance")
    data = json.loads(raw)
    need(raw == canonical(data), "TPC295 canonicality")
    need(data.get("certificate_version") == 1 and
         data.get("claim_status", "").startswith(
             "PROVED_EXACT_FULL_RANK_IMPLIES_SOURCE_CORRELATION"),
         "TPC295 status")
    audit = data.get("payload", {}).get("finite_audit", {})
    need(audit.get("rows") == 18 and audit.get("shell_edges") == 1380,
         "TPC295 finite audit")
    return {
        "tpc295_code_sha256": PARENT_CODE_SHA256,
        "tpc295_result_sha256": PARENT_RESULT_SHA256,
        "engine_code_sha256": ENGINE_CODE_SHA256,
        "tpc295_rows": 18,
        "tpc295_edges": 1380,
    }


def load_parent_rows() -> dict[tuple[int, int, int, int, int], dict[str, Any]]:
    data = json.loads(PARENT_RESULT.read_bytes())
    result: dict[tuple[int, int, int, int, int], dict[str, Any]] = {}
    for row in data["payload"]["rows"]:
        key = (int(row["scale"]), int(row["H"]), int(row["Q"]),
               int(row["comparison_cutoff_z"]), int(row["kernel_exponent"]))
        need(key not in result, "duplicate TPC295 row")
        result[key] = row
    need(len(result) == 18, "TPC295 row map")
    return result


def shell_between(q0: int) -> list[int]:
    return [prime for prime in ENGINE.PRIMES if q0 < prime <= 2 * q0]


def as_mp(value: Fraction | int) -> mp.mpf:
    if isinstance(value, Fraction):
        return mp.mpf(value.numerator) / value.denominator
    return mp.mpf(value)


def enclosure(value: mp.mpf) -> list[str]:
    """A conservative decimal enclosure around a high-precision value."""
    radius = INTERVAL_RELATIVE_RADIUS * max(mp.mpf(1), abs(value))
    return [mp.nstr(value - radius, 32), mp.nstr(value + radius, 32)]


def matrix_from_columns(columns: list[list[Fraction]]) -> mp.matrix:
    return mp.matrix([[as_mp(columns[j][i]) for j in range(len(columns))]
                      for i in range(len(columns[0]))])


def dot(left: mp.matrix, right: mp.matrix) -> mp.mpf:
    return (left.T * right)[0]


def target_metrics(A: mp.matrix, G: mp.matrix, beta: list[Fraction],
                   native: mp.matrix, label: list[int]) -> tuple[dict[str, Any],
                                                                  dict[str, mp.mpf]]:
    m = len(label)
    b = mp.matrix([int(value) for value in label])
    coefficients = mp.lu_solve(G, b)
    h = A * coefficients
    recovered = A.T * h
    correlation_residual = max(abs(recovered[i] - b[i]) for i in range(m))
    cost = dot(b, coefficients)
    source_norm_squared = dot(h, h)
    energy = dot(b, G * b)
    norm_identity_residual = abs(source_norm_squared - cost)

    native_norm_squared = dot(native, native)
    alpha = dot(native, b) / native_norm_squared
    profile_error = mp.sqrt(
        mp.fsum((alpha * native[i] - b[i]) ** 2 for i in range(m)) / m)
    trade_product = cost * energy / (mp.mpf(m) ** 2)
    raw = {
        "least_norm_cost": cost,
        "cost_over_beta_norm_squared": None,
        "profile_ray_rms": profile_error,
        "physical_energy": energy,
        "source_energy_trade_product": trade_product,
        "correlation_residual": correlation_residual,
        "norm_identity_residual": norm_identity_residual,
    }
    return {
        "least_norm_cost": enclosure(cost),
        "cost_over_beta_norm_squared": [],
        "profile_ray_rms": enclosure(profile_error),
        "physical_energy": enclosure(energy),
        "source_energy_trade_product": enclosure(trade_product),
        "correlation_residual_upper": mp.nstr(correlation_residual, 12),
        "norm_identity_residual_upper": mp.nstr(norm_identity_residual, 12),
    }, raw


def build_row(parent_row: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
    mp.mp.dps = MP_DPS
    scale = int(parent_row["scale"])
    height = int(parent_row["H"])
    q0 = int(parent_row["Q"])
    cutoff = int(parent_row["comparison_cutoff_z"])
    exponent = int(parent_row["kernel_exponent"])
    axis = str(parent_row["axis"])
    indices, beta, _ = ENGINE.source_weights(scale, cutoff)
    shell = shell_between(q0)
    columns = [PARENT.physical_output(indices, beta, height, prime, exponent)
               for prime in shell]
    A = matrix_from_columns(columns)
    G = A.T * A
    eigenvalues = mp.eigsy(G, eigvals_only=True)
    eigen_min = eigenvalues[0]
    eigen_max = eigenvalues[len(shell) - 1]
    need(eigen_min > 0, "positive numerical Gram eigenvalue")
    beta_norm_squared = mp.fsum(as_mp(value) ** 2 for value in beta)
    beta_source = mp.matrix([as_mp(value) for value in beta])
    native = A.T * beta_source
    target_specs = (
        ("minimum", [int(value) for value in parent_row["minimum_signed_label"]]),
        ("maxcut", [int(value) for value in parent_row["maxcut_label"]]),
        ("plus", [1] * len(shell)),
    )
    targets: dict[str, dict[str, Any]] = {}
    raw_targets: dict[str, dict[str, mp.mpf]] = {}
    for name, label in target_specs:
        metrics, raw = target_metrics(A, G, beta, native, label)
        metrics["cost_over_beta_norm_squared"] = enclosure(
            raw["least_norm_cost"] / beta_norm_squared)
        raw_targets[name] = raw
        targets[name] = metrics
        need(raw["correlation_residual"] < mp.mpf("1e-45"),
             "source-correlation residual")
        need(raw["norm_identity_residual"] < mp.mpf("1e-45"),
             "least-norm identity residual")
        need(raw["source_energy_trade_product"] >= 1 - mp.mpf("1e-40"),
             "source-energy tradeoff")
    raw_row = {
        "condition_number": eigen_max / eigen_min,
        "eigen_min": eigen_min,
        "eigen_max": eigen_max,
        "beta_norm_squared": beta_norm_squared,
        "targets": raw_targets,
    }
    row = {
        "axis": axis,
        "scale": scale,
        "H": height,
        "Q": q0,
        "comparison_cutoff_z": cutoff,
        "kernel_exponent": exponent,
        "shell": shell,
        "shell_cardinality": len(shell),
        "beta_norm_squared": enclosure(beta_norm_squared),
        "gram_eigenvalue_min": enclosure(eigen_min),
        "gram_eigenvalue_max": enclosure(eigen_max),
        "gram_condition_number": enclosure(eigen_max / eigen_min),
        "declared_budget_ratio_threshold": "1e-3",
        "declared_profile_ray": "span{frozen_beta}",
        "targets": targets,
    }
    return row, raw_row


def build_payload() -> dict[str, Any]:
    lock = parent_lock()
    parent_rows = load_parent_rows()
    ordered = []
    for args, _axis in PARENT.PARENT.ROWS:
        key = tuple(int(value) for value in args)
        need(key in parent_rows, "parent row missing")
        ordered.append(parent_rows[key])
    workers = min(len(ordered), max(1, os.cpu_count() or 1))
    if workers > 1:
        try:
            with mp_pool.get_context("fork").Pool(processes=workers) as pool:
                completed = pool.map(build_row, ordered)
        except (AttributeError, OSError, RuntimeError):
            completed = [build_row(row) for row in ordered]
    else:
        completed = [build_row(row) for row in ordered]
    rows = [item[0] for item in completed]
    raw_rows = [item[1] for item in completed]
    need(len(rows) == 18 and sum(row["shell_cardinality"] for row in rows) >= 0,
         "row census")
    min_budget = [item["targets"]["minimum"][
        "least_norm_cost"] / item["beta_norm_squared"]
                  for item in raw_rows]
    cut_budget = [item["targets"]["maxcut"][
        "least_norm_cost"] / item["beta_norm_squared"]
                  for item in raw_rows]
    plus_budget = [item["targets"]["plus"][
        "least_norm_cost"] / item["beta_norm_squared"]
                   for item in raw_rows]
    min_profile = [item["targets"]["minimum"]["profile_ray_rms"]
                   for item in raw_rows]
    cut_profile = [item["targets"]["maxcut"]["profile_ray_rms"]
                   for item in raw_rows]
    plus_profile = [item["targets"]["plus"]["profile_ray_rms"]
                    for item in raw_rows]
    conditions = [item["condition_number"] for item in raw_rows]
    trade_products = [item["targets"][name]["source_energy_trade_product"]
                      for item in raw_rows
                      for name in ("minimum", "maxcut", "plus")]
    return {
        "schema": SCHEMA,
        "parent_lock": lock,
        "exact_theorem": {
            "least_norm_cost": "min_{A^T h=b} ||h||_2^2 = b^T G^{-1} b",
            "explicit_witness": "h_b=A G^{-1} b",
            "budget_criterion": "target feasible under ||h||_2^2<=B iff b^T G^{-1}b<=B",
            "energy_tradeoff": "(b^T G^{-1}b)(b^T G b) >= (b^T b)^2",
            "profile_ray_projection":
                "min_alpha ||alpha A^T beta-b||_2/sqrt(m)",
            "scope": "unrestricted finite rational source map plus declared one-ray proxy",
        },
        "finite_audit": {
            "rows": 18,
            "shell_edges": 1380,
            "working_precision_decimal_digits": MP_DPS,
            "moduli_inherited_from_tpc295": list(MODULI),
            "declared_budget_ratio_threshold": "1e-3",
            "declared_profile_ray_threshold_rms": "0.9",
            "weighted_minimizer_budget_below_threshold_rows": sum(
                value <= BUDGET_RATIO_THRESHOLD for value in min_budget),
            "maxcut_budget_below_threshold_rows": sum(
                value <= BUDGET_RATIO_THRESHOLD for value in cut_budget),
            "plus_budget_below_threshold_rows": sum(
                value <= BUDGET_RATIO_THRESHOLD for value in plus_budget),
            "weighted_minimizer_profile_ray_rms_at_least_threshold_rows": sum(
                value >= PROFILE_RMS_THRESHOLD for value in min_profile),
            "maxcut_profile_ray_rms_at_least_threshold_rows": sum(
                value >= PROFILE_RMS_THRESHOLD for value in cut_profile),
            "plus_profile_ray_rms_at_most_threshold_rows": sum(
                value <= mp.mpf("0.4") for value in plus_profile),
            "tradeoff_inequality_failures": sum(
                value < 1 - mp.mpf("1e-40") for value in trade_products),
            "weighted_minimizer_budget_ratio_max": enclosure(max(min_budget)),
            "weighted_minimizer_profile_ray_rms_min": enclosure(min(min_profile)),
            "condition_number_max": enclosure(max(conditions)),
            "trade_product_min": enclosure(min(trade_products)),
            "trade_product_max": enclosure(max(trade_products)),
            "one_ray_profile_modeling_choice": "span{frozen_beta}",
            "fixed_power_credit": 0,
        },
        "rows": rows,
        "firewall": {
            "TPC296_LEAST_NORM_IDENTITY": "PROVED_EXACT_FINITE",
            "TPC296_BUDGET_FEASIBILITY_CRITERION": "PROVED_EXACT_FINITE",
            "TPC296_SOURCE_ENERGY_TRADEOFF": "PROVED_EXACT_FINITE",
            "TPC296_COST_ATLAS":
                "NUMERICALLY_CERTIFIED_FINITE_18_ROWS_HIGH_PRECISION_REPLAY",
            "TPC296_UNRESTRICTED_BUDGET_TEST":
                "NUMERICAL_OBSERVATION_FINITE_18_OF_18_BELOW_1E_MINUS_3",
            "TPC296_ONE_RAY_PROFILE_OBSTRUCTION":
                "NUMERICAL_OBSERVATION_FINITE_18_OF_18_RMS_AT_LEAST_0_9",
            "TPC296_CONDITIONING": "NUMERICAL_OBSERVATION_FINITE_MAX_ABOUT_2497",
            "TPC296_NATIVE_RESTRICTED_PROFILE": "OPEN_LITERAL_SOURCE",
            "TPC296_GROWING_SOURCE_BUDGET": "OPEN",
            "TPC296_ARITHMETIC_L2": "OPEN_LITERAL_SOURCE",
            "TPC296_FIXED_POWER_CREDIT": 0,
            "TPC296_FULL_GATE_B": "OPEN",
            "TPC296_TWIN_PRIME_RESULT": "NONE",
            "TPC296_STATUS": STATUS,
        },
        "round2_clue": ROUND2_CLUE,
    }


def frozen_document() -> dict[str, Any]:
    payload = build_payload()
    return {"certificate_version": 1, "claim_status": STATUS,
            "payload": payload,
            "payload_sha256": hashlib.sha256(canonical(payload)).hexdigest()}


def write() -> None:
    RESULT.parent.mkdir(parents=True, exist_ok=True)
    RESULT.write_bytes(canonical(frozen_document()))


def check() -> None:
    raw = RESULT.read_bytes()
    data = json.loads(raw)
    need(raw == canonical(data), "certificate canonicality")
    need(data == frozen_document(), "certificate is not reproducible")
    need(data["payload_sha256"] == hashlib.sha256(
        canonical(data["payload"])).hexdigest(), "payload hash")
    audit = data["payload"]["finite_audit"]
    print("TPC296_CERTIFICATE=PASS rows={} min_budget={} min_profile={} "
          "cond_max={} trade_failures={} fixed_power_credit={}".format(
              audit["rows"],
              audit["weighted_minimizer_budget_below_threshold_rows"],
              audit["weighted_minimizer_profile_ray_rms_at_least_threshold_rows"],
              audit["condition_number_max"],
              audit["tradeoff_inequality_failures"],
              audit["fixed_power_credit"]))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    need(args.write != args.check, "choose exactly one mode")
    if args.write:
        write()
    else:
        check()
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (CheckFailure, OSError, KeyError, TypeError, ValueError,
            json.JSONDecodeError) as error:
        print("TPC296_CERTIFICATE=FAIL " + str(error), file=sys.stderr)
        raise SystemExit(1)
